server: 
  port: 8030
spring: 
  application: 
    name: lcyan-soo
  main: 
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lcyan-soo?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  data:
    jpa:
      repositories:
        # 开启jpa
        enabled: true
        bootstrap-mode: default
  jpa:
    # 数据库方言
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    # 打印SQL
    show-sql: false
    properties:
      # 格式化输出的SQL语句
      hibernate.format_sql: false
    hibernate:
      # 自动建表策略
      ddl-auto: update
  redis: 
    host: 127.0.0.1
    
minio:
  endpoint: http://localhost:9000
  accessKey: admin
  secretKey: admin123456
 
security:
  oauth2:
    client:
      clientId: client
      #clientSecret: secret
      clientSecret: $2a$10$Ymk7habIguPNayz9H/aYXu4laodjwFa5ytS9RIMvMKrS65r8X.V5e
      accessTokenUri: http://localhost:8010/oauth/token
      grant-type: password
      scope: read
    resource:
      jwt:
        keyValue: |
           -----BEGIN PUBLIC KEY-----
           MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAimUKhvBhsoeSM3HkIOP/Y3RXjvonBlZnLj8oO92TyAKG53lmAoK0wZ5MTZPsfrOz2Z7CeAp6mPhUANX2RUoFwVzG7rJmgWyqGmGFNBmtYL+uVqQ80TzWi5zyzXTxgVMWiCqqw/u4AeE1qhN8chnGwhUBnpgPAPd8v57mIwg0n5JxjdYe7pgHlpvt8ZXTXd1KBxB5K7WjNlCfMf75ZEeBaplxsSfJUwKbnHQKWcY3NnpjkVR8y4jviAbkOHmGMaliM7fcsLzbosBUPDQuNlvYdjPBRfH6MMPeXRW6On3u0Um9wIYmkQS+AEgHCq4UuLOnTTqqxnGkwFYeMAAXmRyMtQIDAQAB
           -----END PUBLIC KEY----- 
ignore:
  urls:
    - /
    - /error
    - /favicon.ico
    - /**/*swagger*/**
    - /v2/api-docs
    - /csrf
    - /actuator/**
    - /authentication/**
    - /**/*.css
    - /**/*.js
    - /social
    - /signin
    - /signup
    - /info
    - /health
    - /metrics/**
    - /loggers/**
        
project.version: '@project.version@'