server: 
  port: 8010
spring: 
  application: 
    name: lcyan-auth
  main: 
    allow-bean-definition-overriding: true
  cloud: 
    nacos: 
      discovery: 
        server-addr: 127.0.0.1:8848
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lcyan-auth?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: root
  data:
    jpa:
      repositories:
        # 开启jpa
        enabled: true
        bootstrap-mode: default
  jpa:
    # 数据库方言
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    # 打印SQL
    show-sql: false
    properties:
      # 格式化输出的SQL语句
      hibernate.format_sql: false
    hibernate:
      # 自动建表策略
      ddl-auto: update
  redis: 
    host: 127.0.0.1
security:
  properties:
    client-id: client
    # secret
    client-secret: $2a$10$Ymk7habIguPNayz9H/aYXu4laodjwFa5ytS9RIMvMKrS65r8X.V5e
    grant-type-password: password
    authorization-code: authorization_code
    refresh-token: refresh_token
    implicit: implicit
    scope-read: read
    scope-write: write
    trust: trust
    access-token-validity-seconds: 3600
    refresh-token-validity-seconds: 21600
    
ignore:
  urls:
    - /
    - /error
    - /favicon.ico
    - /**/*swagger*/**
    - /v2/api-docs
    - /csrf
    - /actuator/**
    - /authentication/**
    - /**/*.css
    - /**/*.js
    - /social
    - /signin
    - /signup
    - /info
    - /health
    - /metrics/**
    - /loggers/**
        
project.version: '@project.version@'