server: 
  port: 8020
spring: 
  application: 
    name: lcyan-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lcyan-user?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: yy535930
  data:
    jpa:
      repositories:
        # 开启jpa
        enabled: true
        bootstrap-mode: default
  jpa:
    # 数据库方言
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    # 打印SQL
    show-sql: false
    properties:
      # 格式化输出的SQL语句
      hibernate.format_sql: false
    hibernate:
      # 自动建表策略
      ddl-auto: update
  redis: 
    host: 127.0.0.1

ignore:
  urls:
    - /
    - /error
    - /favicon.ico
    - /**/*swagger*/**
    - /v2/api-docs
    - /csrf
    - /actuator/**
    - /authentication/**
    - /**/*.css
    - /**/*.js
    - /social
    - /signin
    - /signup
    - /info
    - /health
    - /metrics/**
    - /loggers/**

project.version: '@project.version@'