server: 
  port: 8010
spring:
  profiles:
    active: '@spring.profiles.active@'
  main:
    allow-bean-definition-overriding: true
  application: 
    name: 'lcyan-auth-service'
  cloud: 
    nacos: 
      discovery: 
        server-addr: 127.0.0.1:8848
        
project.version: '1.0.0-SNAPSHOT'
